### ISSUE TITLE
Glitchy Interface during Game Play

### ISSUE THREAD

**Issue by nieland22** [haasj22/GameInterfaceStratego#3]
Bug Report by Sierra Nieland: 
After a few moves on the board, multiple squares on the board would be lighting up as an open space to move on both sides of the board during the computer player's turn. It blinked off and on black on certain squares of the board on each side for about 10 seconds, and then the computer player finally made a move. It looked as if the game was spasming, but it still played through the game.

**Comment by haasj22** [comment]
This issue is currently being addressed

**Comment by haasj22** [comment]
Thanks for commenting on this. This was noticed before the alpha but we thought it would allow make the computer seem more humanlike. However, after this morning's feedback, we decided it did more to confuse the user than benefit them so we have since removed this feature.
