### ISSUE TITLE
Shows Opp

### ISSUE THREAD

**Issue by jeanhansen** [haasj22/GameInterfaceStratego#4]
It shows the opponent's values sometimes which I think is cheating.  I don't think you should be able to see what value their pieces are.

**Comment by haasj22** [comment]
We are currently trying to replicate this issue, and once we find the cause of the issue, it will be addressed

**Comment by haasj22** [comment]
After spending a good while playtesting, this glitch was unable to be duplicated. We have included various other bug fixes that may have indirectly patched it out, but for now I feel confident closing this bug. That being said, if it future builds, you can duplicate this bug, please leave another issue and we will get to fixing it ASAP.
