### ISSUE TITLE
Forfeit does not return to menu

### ISSUE THREAD

**Issue by conn22** [haasj22/GameInterfaceStratego#5]
When I hit the forfeit button in the bottom right, it displayed a message that opponent had won and did not return to the menu. This is a minor issue that does not need to be resolved immediately.

**Comment by haasj22** [comment]
We are finding out how to implement this and then this will be addressed

**Comment by haasj22** [comment]
We have learned that this is not a necessary feature and because we have chosen to pursue other ventures, we will the leave the way the game ends as is. Thanks for the report
