### ISSUE TITLE
Field not filling up completely

### ISSUE THREAD

**Issue by JohnsonGlenT** [haasj22/GameInterfaceStratego#6]
Steps to Reproduce:
1. Select Smart AI
2. Play Game.
3. Hit Finalize Setup
4. You Can See you Are Missing 2 Pieces.

Direct consequence:
At disadvantage from start.

Moderate To Major issue.

**Comment by haasj22** [comment]
We will find out why this happens and address it

**Comment by haasj22** [comment]
Thanks for noticing this and giving us thorough steps as how to duplicate it. There was a conditional with the wrong number in it that caused some interesting and undesirable behavior. The current version has fixed this bug.
