### ISSUE TITLE
Notepad automatically populates gameboard

### ISSUE THREAD

**Issue by argiesemann** [haasj22/GameInterfaceStratego#7]
I pressed the notepad button right after the setup screen had disappeared. 

I could draw in the notepad, that was good

when i exited the notepad, I found that the gameboard had been populated, which I imagine is not supposed to happen

**Comment by haasj22** [comment]
If the grader is looking at this and is confused, I'm 99% sure this is Andres Giesemann leaving the issue.

Thanks for informing us about this. I actually was able to find the error earlier tonight. In the button handling switch statement, a break was left out so it flowed into the next case which was the transition turn button. Probably was my favorite glitch to find and fix. Thanks again for your help. The current version of the game has fixed this issue
