### ISSUE TITLE
Piece Placement

### ISSUE THREAD

**Issue by TheCoolBoss** [haasj22/GameInterfaceStratego#8]
Although this may not necessarily be a bug, tapping a square after placing the last piece (of its type) still allows highlights to show after it has been placed.

Example:
Place the flag.
While the flag button is selected, tapping another spot still highlights that square as though it could be placed there.

Possible "fix": Allow moving pieces by tapping another square instead of having to remove it from the board first.

**Comment by hojo21** [comment]
This is not a bug, just how the onclick works within the surface view. This is simply just a preference and our implementation is intentional.
